f=open('test.txt','r')
g=open('test1.txt','r')
h=open('test2.txt','w')
fL=f.readlines()
gL=g.readlines()
n=len(fL)
m=len(gL)
k=max(m,n)
print(k)
f.seek(0)
g.seek(0)
for i in range(k):
    h.write(f.readline()+" "+ g.readline())
f.close()
g.close()
h.close()